language: go

# only build master branch (and PRs)
branches:
  only:
    - "master"

services:
  - redis

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - master

cache:
  directories:
    ${TRAVIS_BUILD_DIR}/vendor
    ${HOME}/.glide

addons:
  apt:
    sources:
      - sourceline: ppa:masterminds/glide
    packages:
      - glide

install:
 - glide update
 - make test test-race coverage minimum-coverage